.TH BPGCOIN-CLI "1" "June 2016" "bpgcoin-cli 0.12"
.SH NAME
bpgcoin-cli \- a remote procedure call client for BPG Coin. 
.SH SYNOPSIS
bpgcoin-cli [options] <command> [params] \- Send command to BPG Coin. 
.TP
bpgcoin-cli [options] help \- Asks BPG Coin for a list of supported commands.
.SH DESCRIPTION
This manual page documents the bpgcoin-cli program. bpgcoin-cli is an RPC client used to send commands to BPG Coin.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbpgcoind\fP, \fBbpgcoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
